version: "3.7"
services:
  db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
